/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate } from '../types.js';
import {
  OPSX_CLI_QUERY_CONTEXT,
  OPENSPEC_PHILOSOPHY,
  OPSX_SHARED_CONTEXT,
  VERIFY_CLI_JSON_SCHEMA_REFERENCE,
  VERIFY_ERROR_RECOVERY_GUIDE,
  VERIFY_STATE_MACHINE_DIAGRAM,
} from '../fragments/opsx-fragments.js';

const APPLY_STEP_1_PREPARATION_REFERENCE = `
# Apply Step 1: Preparation

1. Select the change. If no clear name is provided, infer only from explicit context; otherwise run \`openspec list --json\` and ask. Always announce "Using change: <name>".
2. Run \`openspec status --change "<name>" --json\` and \`openspec instructions apply --change "<name>" --json\`. Read \`configProjection.prompt.fragments\` for \`proseLanguage\` and \`apply.defaultIsolation\`. Handle \`state: "needs_verify"\` by skipping to Phase 1 and \`state: "needs_seal"\` by continuing with Phase 2/3.
3. Load shared OPSX context before reading change artifacts.
${OPSX_SHARED_CONTEXT}
4. Read every context file listed by the CLI. Inspect \`changeDir/.verify-result.json\` and \`## Remediation\`; unresolved CRITICAL/code_fix/artifact_fix items take priority.
5. Use CLI-backed OPSX navigation after shared context.
${OPSX_CLI_QUERY_CONTEXT}
`.trim();

const APPLY_STEP_2_PREFLIGHT_SCAN_REFERENCE = `
# Apply Step 2: Pre-flight Scan

Before entering branch isolation, scan all tasks in tasks.md for contradictions and dependency-ordering issues across Goals, Files, Requirements, and Checks:
- Conflicting declarations on the same file or interface across different tasks
- Task declarations that conflict with change-local specs or design.md
- Earlier task depending on output of a later task, for example Task N's Files declares Modify on a path created by Task M's Files where M > N
- Present all findings at once; proceed silently when the scan is clean
`.trim();

const APPLY_STEP_3_BRANCH_ISOLATION_REFERENCE = `
# Apply Step 3: Branch Isolation

Run \`git branch --show-current\`. On main/master ask whether to Create branch \`<change-name>\`, Create worktree at \`.worktrees/<change-name>\`, or continue; config branch/worktree/none use that as the default choice without prompting; only \`ask\` is interactive and means prompt.

Persist \`path.join(changeDir, '.apply-isolation.json')\` with \`method\`, \`branchName\`, optional \`worktreePath\`, and \`originalBranch\`. Use using-git-worktrees when present.
`.trim();

const APPLY_STEP_4_PHASE1_VERIFICATION_REFERENCE = `
# Apply Step 4: Phase 1 Verification

Delegate to the clean-context \`openspec-reviewer\` agent with \`context: "fresh"\`; persist \`openspec verify phase1 "<change-name>" --input '<json>' --json\`, and write back only CRITICAL remediation.
`.trim();

const APPLY_STEP_5_PHASE2_OPTIMIZATION_REFERENCE = `
# Apply Step 5: Phase 2 Optimization

Use git commits as checkpoints; never use stash or tags.

1. Skip only for \`--skip-optimization\` or \`optimization.enabled: false\`; record \`SKIPPED\`.
2. Read \`optimization.optRetries\`; it limits failures of one finding direction. Successful findings do not consume optRetries.
3. Save the Phase 1 baseline:
   \`\`\`bash
   git add -A
   git commit -m "wip: opt-checkpoint-r0 (baseline)"
   \`\`\`
4. Delegate to fresh \`openspec-optimizer\` with changeName, absolute changeDir, and absolute projectRoot. Submit its strict optimizer reconciliation envelope:
   \`\`\`bash
   openspec verify phase2 "<change-name>" --type=optimization --input '<json>' --json
   \`\`\`
5. If optimizer returns blockingObservations, return to Phase 1 remediation. If no finding is selected, Phase 2 is terminal. Otherwise read selected finding evidence, keyDesign, preservationConstraints, validation, and priorityReason.
6. If project evidence contradicts the finding or keyDesign, submit masterChallenge and re-run fresh optimizer reconciliation. Do not skip or reject it yourself.
7. Before editing, enforce selected-target freshness:
   \`\`\`bash
   openspec verify phase2 "<change-name>" --type=optimization --input '{"status":"OPTIMIZATION_PROPOSED","mode":"begin-implementation","findingId":"<finding-id>"}' --json
   \`\`\`
8. Master implements only the selected finding with TDD. Preserve the finding's constraints and record any non-substantive implementation differences.
9. Delegate to fresh \`openspec-reviewer\` for speculative verification. It verifies specs and preservationConstraints, not optimization value. Persist its verdict:
   \`\`\`bash
   openspec verify phase2 "<change-name>" --type=verification --input '{"result":"PASS","findingId":"<finding-id>","issues":[]}' --json
   \`\`\`
10. On PASS, save the successful checkpoint, then re-run optimizer reconciliation against current code:
    \`\`\`bash
    git add -A
    git commit -m "wip: opt-r\${N} (\${findingId}: \${description})"
    \`\`\`
11. On FAIL, restore the latest successful checkpoint with \`git reset --hard HEAD\` and \`git clean -fd\`, then re-run optimizer reconciliation. A direction reaching optRetries becomes rejected; other findings continue.
12. Stop on no actionable findings, all remaining findings terminal/deferred, skip/disabled, or STALLED. Keep all \`wip: opt-*\` commits.

${VERIFY_CLI_JSON_SCHEMA_REFERENCE}
${VERIFY_ERROR_RECOVERY_GUIDE}
${VERIFY_STATE_MACHINE_DIAGRAM}
`.trim();

const APPLY_STEP_6_PHASE3_SEAL_REFERENCE = `
# Apply Step 6: Phase 3 Seal

Run \`openspec verify seal "<change-name>" --json\`. If seal fails, preserve diagnostics, convert them into remediation context, map the remediation to the affected task, and return to Phase 0 recovery. Do not pause on the first seal failure.
`.trim();

const APPLY_STEP_7_OUTPUT_REFERENCE = `
# Apply Step 7: Output

Report schema, progress, current task, completed tasks this session, and final sealed/archive-ready status. Keep edits minimal, use Node path handling for generated paths, update task checkboxes only after evidence passes, and preserve canonical artifact headings/tokens and configured document language projection.
`.trim();

export function getApplyChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-apply-change',
    description: 'Implement tasks from an OpenSpec change. Use when the user wants to start implementing, continue implementation, or work through tasks.',
    instructions: `Implement tasks from an OpenSpec change.

${OPENSPEC_PHILOSOPHY}

For workflow-managed writes, read the resolved file definition before its instruction and template, and MUST NOT copy definitions, config projections, or reasoning into artifacts.

## Flow Outline

1. Step 1: Preparation — read \`openspec/references/openspec-apply-step-1-preparation.md\`.
2. Step 2: Pre-flight scan — read \`openspec/references/openspec-apply-step-2-preflight-scan.md\`.
3. Step 3: Branch isolation — read \`openspec/references/openspec-apply-step-3-branch-isolation.md\`.
4. Execute tasks with the implementation discipline below.
5. Step 4: Phase 1 verification — read \`openspec/references/openspec-apply-step-4-phase1-verification.md\` and delegate to the clean-context \`openspec-reviewer\` agent.
6. Step 5: Phase 2 optimization — read \`openspec/references/openspec-apply-step-5-phase2-optimization.md\` and delegate to the clean-context \`openspec-optimizer\` agent when eligible.
7. Step 6: Phase 3 seal — read \`openspec/references/openspec-apply-step-6-phase3-seal.md\`.
8. Step 7: Output — read \`openspec/references/openspec-apply-step-7-output.md\`.

## Implementation Discipline

- Write or update targeted tests before behavior/code changes.
- Verify the expected failure before implementation, then rerun the same check after the minimal fix.
- Prefer deletion, standard library, native platform support, installed dependencies, and direct expressions before adding new code.
- Do not add abstractions, dependencies, or files unless the spec or failing test requires them.
- Exercise public behavior; mock only system boundaries injected through parameters.
- Preserve canonical artifact headings, schema keys, IDs, commands, and template tokens exactly.
- Treat failures as recovery feedback: read the full error, isolate the layer, compare a working pattern, state one hypothesis, change one variable, and rerun the same check.
- Pause after repeated identical failures or three failed fix attempts.

When Phase 3 seal passes, end with an explicit call-to-action: \`Archive ready. Run /opsx:archive <change-name> to complete the workflow.\``,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
    referenceFiles: [
      { path: 'references/apply-step-1-preparation.md', content: APPLY_STEP_1_PREPARATION_REFERENCE },
      { path: 'references/apply-step-2-preflight-scan.md', content: APPLY_STEP_2_PREFLIGHT_SCAN_REFERENCE },
      { path: 'references/apply-step-3-branch-isolation.md', content: APPLY_STEP_3_BRANCH_ISOLATION_REFERENCE },
      { path: 'references/apply-step-4-phase1-verification.md', content: APPLY_STEP_4_PHASE1_VERIFICATION_REFERENCE },
      { path: 'references/apply-step-5-phase2-optimization.md', content: APPLY_STEP_5_PHASE2_OPTIMIZATION_REFERENCE },
      { path: 'references/apply-step-6-phase3-seal.md', content: APPLY_STEP_6_PHASE3_SEAL_REFERENCE },
      { path: 'references/apply-step-7-output.md', content: APPLY_STEP_7_OUTPUT_REFERENCE },
    ],
  };
}
