/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate } from '../types.js';
import {
  OPSX_CLI_QUERY_CONTEXT,
  OPSX_COMPILATION_PHILOSOPHY,
  OPSX_SHARED_CONTEXT,
  VERIFY_CLI_JSON_SCHEMA_REFERENCE,
  VERIFY_ERROR_RECOVERY_GUIDE,
  VERIFY_STATE_MACHINE_DIAGRAM,
} from '../fragments/opsx-fragments.js';

const APPLY_STEP_1_PREPARATION_REFERENCE = `
# Apply Step 1: Preparation

1. Select the change. If no clear name is provided, infer only from explicit context; otherwise run \`openspec list --json\` and ask. Always announce "Using change: <name>".
2. Run \`openspec status --change "<name>" --json\` and \`openspec instructions apply --change "<name>" --json\`. Read \`configProjection.prompt.fragments\` for \`proseLanguage\` and \`apply.defaultIsolation\`. Handle \`state: "needs_verify"\` by skipping to Phase 1 and \`state: "needs_seal"\` by continuing with Phase 2/3.
3. Load shared OPSX context before reading change artifacts.
${OPSX_SHARED_CONTEXT}
4. Read every context file listed by the CLI. Inspect \`changeDir/.verify-result.json\` and \`## Remediation\`; unresolved CRITICAL/code_fix/artifact_fix items take priority.
5. Use CLI-backed OPSX navigation after shared context.
${OPSX_CLI_QUERY_CONTEXT}
`.trim();

const APPLY_STEP_2_PREFLIGHT_SCAN_REFERENCE = `
# Apply Step 2: Pre-flight Scan

Before entering branch isolation, scan all tasks in tasks.md for contradictions and dependency-ordering issues across Goals, Files, Requirements, and Checks:
- Conflicting declarations on the same file or interface across different tasks
- Task declarations that conflict with change-local specs or design.md
- Earlier task depending on output of a later task, for example Task N's Files declares Modify on a path created by Task M's Files where M > N
- Present all findings at once; proceed silently when the scan is clean
`.trim();

const APPLY_STEP_3_BRANCH_ISOLATION_REFERENCE = `
# Apply Step 3: Branch Isolation

Run \`git branch --show-current\`. On main/master ask whether to Create branch \`<change-name>\`, Create worktree at \`.worktrees/<change-name>\`, or continue; config branch/worktree/none use that as the default choice without prompting; only \`ask\` is interactive and means prompt.

Persist \`path.join(changeDir, '.apply-isolation.json')\` with \`method\`, \`branchName\`, optional \`worktreePath\`, and \`originalBranch\`. Use using-git-worktrees when present.
`.trim();

const APPLY_STEP_4_PHASE1_VERIFICATION_REFERENCE = `
# Apply Step 4: Phase 1 Verification

Delegate to the clean-context \`openspec-reviewer\` agent with \`context: "fresh"\`; persist \`openspec verify phase1 "<change-name>" --input '<json>' --json\`, and write back only CRITICAL remediation.
`.trim();

const APPLY_STEP_5_PHASE2_OPTIMIZATION_REFERENCE = `
# Apply Step 5: Phase 2 Optimization

The checkpoint is a git commit, not a git stash entry or git tag. Do not create stash or tag checkpoints for apply optimization.

1. Skip Phase 2 only when the user requested \`--skip-optimization\` or \`optimization.enabled: false\`; record \`SKIPPED\` through \`openspec verify phase2\`.
2. Read \`optimization.optRetries\` from \`openspec/config.yaml\`; default to \`2\`.
3. Before the first optimization attempt, save the Phase 1 baseline:
   \`\`\`bash
   git add -A
   git commit -m "wip: opt-checkpoint-r0 (baseline)"
   \`\`\`
4. Delegate to the clean-context \`openspec-optimizer\` agent with \`context: "fresh"\`. Pass Phase 1 result, artifacts, file contents, config, and failedDirections. The optimizer proposes Search/Replace blocks only; it MUST NOT edit files.
5. Read the rationale tags (delete/stdlib/native/yagni/shrink) and Code Smell annotations on each proposed block. Understand the optimization rationale before proceeding.
6. For each proposed optimization, record pre-patch hashes before editing, while the working tree is still pre-patch:
   \`\`\`bash
   openspec verify phase2 "<change-name>" --type=optimization --files "<affected-files>" --input '<json>' --json
   \`\`\`
7. Apply Search/Replace blocks atomically, then spawn the reviewer agent for speculative Phase 1 re-verification.
8. On speculative PASS, record verification PASS and save the new successful state before deciding whether to continue. This verification call happens after patching:
   \`\`\`bash
   openspec verify phase2 "<change-name>" --type=verification --input '<json>' --json
   git add -A
   git commit -m "wip: opt-r\${N} (\${description})"
   \`\`\`
9. On speculative FAIL, restore the latest commit:
   \`\`\`bash
   git reset --hard HEAD
   git clean -fd
   \`\`\`
   Record the failed direction in \`.verify-result.json\`.
10. Each complete proposal + patch + reviewer re-verify loop consumes one \`optRetries\` budget, whether it passes or fails. Format or Search/Replace matching problems are handled by the main agent and do not consume retry budget.
11. When all attempts finish, keep all \`wip: opt-*\` commits as audit history.

${VERIFY_CLI_JSON_SCHEMA_REFERENCE}
${VERIFY_ERROR_RECOVERY_GUIDE}
${VERIFY_STATE_MACHINE_DIAGRAM}
`.trim();

const APPLY_STEP_6_PHASE3_SEAL_REFERENCE = `
# Apply Step 6: Phase 3 Seal

Run \`openspec verify seal "<change-name>" --json\`. If seal fails, preserve diagnostics, convert them into remediation context, map the remediation to the affected task, and return to Phase 0 recovery. Do not pause on the first seal failure.
`.trim();

const APPLY_STEP_7_OUTPUT_REFERENCE = `
# Apply Step 7: Output

Report schema, progress, current task, completed tasks this session, and final sealed/archive-ready status. Keep edits minimal, use Node path handling for generated paths, update task checkboxes only after evidence passes, and preserve canonical artifact headings/tokens and configured document language projection.
`.trim();

export function getApplyChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-apply-change',
    description: 'Implement tasks from an OpenSpec change. Use when the user wants to start implementing, continue implementation, or work through tasks.',
    instructions: `Implement tasks from an OpenSpec change.

${OPSX_COMPILATION_PHILOSOPHY}

## Flow Outline

1. Step 1: Preparation — read \`openspec/references/openspec-apply-step-1-preparation.md\`.
2. Step 2: Pre-flight scan — read \`openspec/references/openspec-apply-step-2-preflight-scan.md\`.
3. Step 3: Branch isolation — read \`openspec/references/openspec-apply-step-3-branch-isolation.md\`.
4. Execute tasks with the implementation discipline below.
5. Step 4: Phase 1 verification — read \`openspec/references/openspec-apply-step-4-phase1-verification.md\` and delegate to the clean-context \`openspec-reviewer\` agent.
6. Step 5: Phase 2 optimization — read \`openspec/references/openspec-apply-step-5-phase2-optimization.md\` and delegate to the clean-context \`openspec-optimizer\` agent when eligible.
7. Step 6: Phase 3 seal — read \`openspec/references/openspec-apply-step-6-phase3-seal.md\`.
8. Step 7: Output — read \`openspec/references/openspec-apply-step-7-output.md\`.

## Implementation Discipline

- Write or update targeted tests before behavior/code changes.
- Verify the expected failure before implementation, then rerun the same check after the minimal fix.
- Prefer deletion, standard library, native platform support, installed dependencies, and direct expressions before adding new code.
- Do not add abstractions, dependencies, or files unless the spec or failing test requires them.
- Exercise public behavior; mock only system boundaries injected through parameters.
- Preserve canonical artifact headings, schema keys, IDs, commands, and template tokens exactly.
- Treat failures as recovery feedback: read the full error, isolate the layer, compare a working pattern, state one hypothesis, change one variable, and rerun the same check.
- Pause after repeated identical failures or three failed fix attempts.

When Phase 3 seal passes, end with an explicit call-to-action: \`Archive ready. Run /opsx:archive <change-name> to complete the workflow.\``,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
    referenceFiles: [
      { path: 'references/apply-step-1-preparation.md', content: APPLY_STEP_1_PREPARATION_REFERENCE },
      { path: 'references/apply-step-2-preflight-scan.md', content: APPLY_STEP_2_PREFLIGHT_SCAN_REFERENCE },
      { path: 'references/apply-step-3-branch-isolation.md', content: APPLY_STEP_3_BRANCH_ISOLATION_REFERENCE },
      { path: 'references/apply-step-4-phase1-verification.md', content: APPLY_STEP_4_PHASE1_VERIFICATION_REFERENCE },
      { path: 'references/apply-step-5-phase2-optimization.md', content: APPLY_STEP_5_PHASE2_OPTIMIZATION_REFERENCE },
      { path: 'references/apply-step-6-phase3-seal.md', content: APPLY_STEP_6_PHASE3_SEAL_REFERENCE },
      { path: 'references/apply-step-7-output.md', content: APPLY_STEP_7_OUTPUT_REFERENCE },
    ],
  };
}
