/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate } from '../types.js';
import { OPSX_COMPILATION_PHILOSOPHY } from '../fragments/opsx-fragments.js';
import {
  SUBAGENT_VERIFY_EXECUTION_MODEL,
  type VerifyExecutionModel,
} from './verify-execution-model.js';

const ARCHIVE_COMMIT_MESSAGE_REFERENCE_PATH = 'references/archive-commit-message.md';
const BOUNDARY_COMMIT_MESSAGE_REFERENCE_PATH = 'references/boundary-commit-message.md';
const MERGE_SUMMARY_MESSAGE_REFERENCE_PATH = 'references/merge-summary-message.md';
const ARCHIVE_COMMIT_MESSAGE_SHARED_PATH = 'openspec/references/openspec-archive-commit-message.md';
const BOUNDARY_COMMIT_MESSAGE_SHARED_PATH = 'openspec/references/openspec-boundary-commit-message.md';
const MERGE_SUMMARY_MESSAGE_SHARED_PATH = 'openspec/references/openspec-merge-summary-message.md';

const BOUNDARY_COMMIT_MESSAGE_REFERENCE = `
# Boundary Commit Message Template

Use this built-in format when \`git.commitMessage.boundary\` is not configured.

Subject:

\`\`\`text
<type>(<scope>): <English subject>
\`\`\`

Body:

\`\`\`text
## Why
[Business context] <why from proposal.md>
[Technical decision] <decision from design.md when present>

## Changes
- \`<file-path>\`: <why this file changed>
\`\`\`

Footer:

\`\`\`text
Implementation: <base>..<head> (carried by <commits>)
\`\`\`

Rules:
- Build \`## Why\` from the archived \`proposal.md\` and \`design.md\` (when present).
- Build \`## Changes\` from \`git diff --name-only <base>..<head>\` file list cross-referenced with archived \`tasks.md\` Files/Goal and \`opsx-delta.yaml\`.
- List all files from the diff; if a file is not mentioned in archived artifacts, state that explicitly.
- The \`<base>\` is the prior change boundary (prior archive/boundary commit); the agent infers it from git history.
- The \`Implementation:\` footer lists the effective diff range and the commits carrying that diff (including \`wip: opt-*\` checkpoint commits and any just-created normal implementation commit).
- Use \`git commit -F -\` to pass the message.
- Always create this commit with \`git commit --allow-empty\`; it may be intentionally empty when all implementation diff is carried by checkpoint commits.
`.trim();

const ARCHIVE_COMMIT_MESSAGE_REFERENCE = `
# Archive Commit Message Template

Use this built-in format when \`git.commitMessage.archive\` is not configured.

Subject:

\`\`\`text
docs(<change-name>): Archive change artifacts
\`\`\`

Body:

\`\`\`text
## Why
[Business context] <why this archive commit is needed>

## Changes
- \`<file-path>\`: <why this archived/synced path must be committed>
\`\`\`

Rules:
- Include only archive/synced paths selected for the archive commit.
- Keep non-archive dirty changes out of the commit.
- Pass the message through \`git commit -F -\`.
`.trim();

const MERGE_SUMMARY_MESSAGE_REFERENCE = `
# Merge Summary Message Template

Use this built-in format when \`git.commitMessage.merge\` is not configured.

Subject:

\`\`\`text
<type>(<scope>): <English subject>
\`\`\`

Body:

\`\`\`text
## Why
[Business context] <why from proposal.md>
[Technical decision] <decision from design.md when present>

## Changes
- \`<file-path>\`: <why this file changed>
\`\`\`

Rules:
- Build the summary from the archived \`proposal.md\`, \`design.md\`, \`tasks.md\`, and \`opsx-delta.yaml\`.
- Use \`git commit -F -\` for no-ff merge commits and squash commits that require a message.
- Do not generate this message for \`ff-only\` merges.
`.trim();

function buildArchiveFullVerifyContract(_executionModel: VerifyExecutionModel): string {
  return `   When the verify result is missing or stale, execute the same verify contract as \`/opsx:verify\` using the \`${SUBAGENT_VERIFY_EXECUTION_MODEL}\` skeleton:
   - Determine \`changeName\`, absolute \`changeDir\`, and absolute \`projectRoot\`
   - Delegate to clean-context generated \`openspec-reviewer\` subagent with \`context: "fresh"\`; pass only \`changeName\`, \`changeDir\`, \`projectRoot\`, and the explicit evidence bundle required for canonical Phase 1
   - Validate the reviewer payload, apply only deterministic \`tasks.md\` write-back in the main workspace, and persist the canonical Phase 1 payload
   - Execute the verify workflow end-to-end; when Phase 2 is eligible, delegate to clean-context generated \`openspec-optimizer\` subagent with \`context: "fresh"\`; pass only \`changeName\`, \`changeDir\`, \`projectRoot\`, Phase 1 result, artifacts, file contents, config, and failedDirections
   - In \`P1_SPECULATIVE_FENCE\`, delegate to clean-context generated \`openspec-reviewer\` subagent again with \`context: "fresh"\`, \`changeName\`, \`changeDir\`, and \`projectRoot\` for the speculative verdict
   - The top-level archive flow MUST NOT inline a current-agent review skeleton or silently downgrade to reread mode`;
}

function buildAgentGitFlowStep(): string {
  return `   The agent continues the post-archive git flow. First handle the implementation boundary before OpenSpec/docs archive artifacts. If uncommitted real project implementation changes remain, create a normal implementation commit that contains only those changes. Then always create a semantic boundary commit with \`git commit --allow-empty\`; this boundary commit may be intentionally empty when the effective implementation diff is already carried by retained \`wip: opt-*\` checkpoint commits. If \`git.commitMessage.boundary\` is set, read that project-relative path; otherwise read the project-root file \`${BOUNDARY_COMMIT_MESSAGE_SHARED_PATH}\`. Use that template to build the boundary commit message and run \`git commit -F -\` for the boundary commit. If \`git.commitMessage.archive\` is set, read that project-relative path; otherwise read the project-root file \`${ARCHIVE_COMMIT_MESSAGE_SHARED_PATH}\`. Use that template before creating the OpenSpec/docs archive commit, add only archive/synced paths, and run \`git commit -F -\`. If a merge or squash commit message is needed, prepare it from the configured or built-in merge template. If \`git.commitMessage.merge\` is set, read that project-relative path; otherwise read the project-root file \`${MERGE_SUMMARY_MESSAGE_SHARED_PATH}\`. Apply \`git.merge.strategy\` with \`git merge --no-ff\`, \`git merge --ff-only\`, or \`git merge --squash\` as appropriate. Use \`git.branch.deleteAfterArchive\` only after confirming the branch is merged with \`git branch --merged\`. Build paths with \`path.join()\`, \`path.resolve()\`, and \`path.normalize()\`.`;
}

function buildArchiveInstructions(
  inputLine: string,
  executionModel: VerifyExecutionModel
): string {
  return `Archive a completed change in the experimental workflow.

${OPSX_COMPILATION_PHILOSOPHY}

**Input**: ${inputLine}

Before archiving, run \`openspec config project --json\` and consume git policy from its normalized project config: \`git.commitMessage.archive\`, \`git.commitMessage.merge\`, \`git.merge.strategy\`, and \`git.branch.deleteAfterArchive\`; do not parse raw YAML inside the skill.

**Steps**

1. **Select change**
   If no clear change name is provided, run \`openspec list --json\`, show active changes with schema, and ask. Do not guess.

2. **Unified Full Verify Gate**
   Run \`openspec verify status "<change-name>" --json\`. Treat \`freshness.status\` as the sole signal for rerunning full verify: only \`MISSING\` or \`STALE\` enters Step 2.5. MUST NOT infer staleness from \`checks\`, \`details\`, or \`information\`. A \`FRESH\` result after seal MUST reuse Phase 1 even when Git HEAD information differs. For a fresh result, resolve incompatible optimization states separately: complete \`PENDING_VERIFICATION\` through the appropriate \`openspec verify phase2\` call, and hard-stop \`ABORTED_UNSAFE\` for manual recovery.

2.5. **Execute Full Verify**

${buildArchiveFullVerifyContract(executionModel)}
   Continue through Phase 2 when eligible; \`SKIPPED\` is valid only for config/user skip. Persist fresh verify before archiving.

3. **Check artifact completion status**
   Run \`openspec status --change "<name>" --json\`. Warn and confirm before proceeding if any artifact is not \`done\`.

4. **Check task completion status**
   Read \`tasks.md\`; warn and confirm before proceeding if incomplete checkboxes remain. Missing tasks are not a task-related blocker.

5. **Assess delta sync state**
   If delta specs or \`opsx-delta.yaml\` exist, assess whether sync is required. The archive CLI performs verify, sync, and move-to-archive; do not duplicate sync writes manually.

6. **Run archive CLI**
   Run \`openspec archive "<change-name>"\` after the verify gate is fresh. CLI only verifies, syncs, moves the change to archive, and prints the git handoff reminder. CLI MUST NOT create commits, merge branches, switch branches, delete branches, remove worktrees, or generate commit messages.

7. **Git handoff**
   Read the archive CLI output and the projected git policy from \`openspec config project --json\`. Summary fields include change name, schema, archive location, verify gate result, specs / OPSX sync result, agent-owned git follow-up status, and merge strategy.

8. **Agent git flow**
${buildAgentGitFlowStep()}

9. **Display summary**
   Include change, schema, archive location, verify gate result, specs / OPSX sync result, agent-owned git follow-up status, Merge Strategy, cleanup responsibility, verify reuse/reexecution, and warnings. Do not report that CLI created an archive commit, performed a merge, or deleted a feature branch.

**Output On Success**

\`\`\`
## Archive Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Archived to:** openspec/changes/archive/YYYY-MM-DD-<name>/
**Verify Gate:** Fresh PASS or PASS_WITH_WARNINGS result confirmed
**Specs / OPSX:** ✓ Synced to main specs and project OPSX (or "No deltas" or "Sync gate bypassed with --no-sync")
**Agent Git Follow-up:** <completed / pending with reason>
**Merge Strategy:** <git.merge.strategy>
**Cleanup Responsibility:** <agent>

Archive completed after satisfying the unified full verify gate.
\`\`\`

**Guardrails**
- Always prompt for change selection if not provided
- Prioritize the standard verify gate; only pass \`--no-verify\` to the archive CLI when the user explicitly requests it (the CLI provides its own confirmation prompt)
- Show clearly whether verify was reused or re-executed
- In \`core\`, use \`openspec sync "<change-name>"\` rather than manual inline sync
- If delta specs or \`opsx-delta.yaml\` exist, always run the shared sync assessment before moving the change directory`;
}

export function createArchiveChangeSkillTemplateForExecutionModel(
  executionModel: VerifyExecutionModel = SUBAGENT_VERIFY_EXECUTION_MODEL
): SkillTemplate {
  return {
    name: 'openspec-archive-change',
    description:
      'Archive a completed change in the experimental workflow. Use when the user wants to finalize and archive a completed change after implementation is complete.',
    instructions: buildArchiveInstructions(
      'Optionally specify a change name. If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.',
      executionModel
    ),
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
    referenceFiles: [
      {
        path: ARCHIVE_COMMIT_MESSAGE_REFERENCE_PATH,
        content: ARCHIVE_COMMIT_MESSAGE_REFERENCE,
      },
      {
        path: BOUNDARY_COMMIT_MESSAGE_REFERENCE_PATH,
        content: BOUNDARY_COMMIT_MESSAGE_REFERENCE,
      },
      {
        path: MERGE_SUMMARY_MESSAGE_REFERENCE_PATH,
        content: MERGE_SUMMARY_MESSAGE_REFERENCE,
      },
    ],
  };
}

export function getArchiveChangeSkillTemplate(): SkillTemplate {
  return createArchiveChangeSkillTemplateForExecutionModel();
}
