/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate } from '../types.js';
import {
  ELEMENT_DEFINITION_SEMANTICS,
  XIRANG_PHILOSOPHY,
  XIRANG_SHARED_CONTEXT,
} from '../fragments/xirang-fragments.js';

const CONVERSATION_LANGUAGE_GUIDANCE = `Output language: use the user's main language for prose and non-canonical section labels; keep commands, paths, artifact names, schema keys, and Xirang tokens unchanged.`;

const ACTIVE_CHANGE_CAPTURE_GUIDANCE = `### Capture Boundary for Existing Changes

When exploring an active change, read proposal/design/tasks and its Delta units, reference them naturally, and classify insights by where a future workflow should capture them. Do not update those artifacts in explore.

| Insight Type                         | Future Capture Target                          |
|--------------------------------------|------------------------------------------------|
| Observable behavior requirement      | \`elements/<identity>.md\` body                 |
| Observable behavior changed          | \`elements/<identity>.md\` body                 |
| Refactor rationale or rejected path  | \`design.md\`                                   |
| Implementation strategy              | \`design.md\`                                   |
| Scope changed                        | \`proposal.md\`                                 |
| New work or verification identified  | \`tasks.md\`                                    |
| Element identity or hierarchy changed | \`elements/<identity>.md\` frontmatter          |
| Relationship changed                 | \`relationships/<relationship kind identity>.yaml\` |
| Element Kind or Relationship Kind changed | \`metamodel/<kind identity>.md\`           |
| Authored View changed                | \`views/<view identity>.md\`                    |
| Assumption invalidated               | Relevant artifact                              |
| Test needs update or deletion        | \`tasks.md\` + \`design.md\`                     |

Example offers:
- "That is a design decision for \`design.md\`; include it in the Design Summary, then call \`/xirang:propose <change-name>\` or the appropriate non-explore workflow."
- "This changes an Element Contract; include it in the Design Summary, then call \`/xirang:propose <change-name>\` or the appropriate non-explore workflow."
- "This changes scope for \`proposal.md\`; include it in the Design Summary, then call \`/xirang:propose <change-name>\` or the appropriate non-explore workflow."`;

const EXPLORE_SUPPERPOWERS_STYLE_REFERENCE = `# Superpowers-Style Explore Behavior Guide

This reference is the Xirang explore adaptation of Superpowers brainstorming. It restores design-first discipline but does not restore original Superpowers file writing, committing, or implementation planning permissions.

## Superpowers brainstorming source

The core of Superpowers brainstorming is not free-form discussion, but compressing vague ideas into user-confirmed designs before implementation:
- Read project context first, then determine problem boundaries.
- Ask exactly one clarification question at a time.
- For key choices, present 2-3 approaches with trade-offs and a recommendation.
- Present design section by section; wait for user confirmation on each.
- Self-review the design, then hand off for user review.
- Enter the next workflow through explicit handoff.

If todo is available, track these stages as a checklist and tick each completed stage.

Xirang mapping:
- The original design-document step maps to a conversation-only \`Design Summary\`.
- The original commit step is removed. Explore may persist only a user-confirmed Change Structural Definition through the Xirang-owned Definition Framing protocol; it does not directly write files.
- The original implementation-plan handoff maps to \`xirang-propose\` handoff.

## Conversation language

${CONVERSATION_LANGUAGE_GUIDANCE}

## Hard gate before implementation

Do not implement before design confirmation is complete.

Do not start coding, generate patches, directly update artifacts, or interpret design confirmations as write authorization during Explore. Even if the user says "ok", "that works", or chooses an option, it only confirms the design direction. Definition Framing persistence requires a separate explicit confirmation under the Xirang-owned protocol.

Simple changes still require design confirmation. For a narrow change, confirm only the applicable design sections, but do not skip the process: at minimum confirm the problem, impact scope, approach, and verification method.

## Project context exploration

**Evidence-first discipline**: All claims about existing code, architecture, or technical decisions must be grounded in project evidence. Do not substitute general knowledge for project facts.

Before context reads, create the todo checklist: context, visual decision, one question, options, section approvals, self-review, handoff.

Constrain the discussion with project facts first:
- Read relevant Xirang change, Element Contract, design, and tasks.
- Inspect relevant implementation files, tests, and git evidence.
- Identify affected subsystems; if the request spans multiple independent subsystems, first clarify boundaries and recommend an order.
- Explicitly identify unknowns; do not substitute general experience for project evidence.

## Just-in-time visual companion

Use visual expression only when it reduces complexity. Suitable scenarios:
- Architectural boundaries, state machines, data flow, dependency relationships.
- Multi-option comparison.
- When the user is stuck on abstract relationships.

For routine CLI behavior, narrow fixes, field naming, or test selection, use concise text or tables; do not introduce a browser or server companion.

## One-question discipline

Ask only one design-changing question per turn, then wait for the answer. Do not bundle scope, API, data model, and testing strategy into a string of questions.

If the choice set is clear, prefer presenting 2-3 options with differences explained; if unclear, first ask one question that narrows the problem space.

## 2-3 approaches

Provide 2-3 approaches for key design decisions. Each option includes:
- Description.
- Strengths.
- Weaknesses or risks.
- Best-fit scenario.

When giving a recommendation, explain why and tie it to project constraints, not personal preference.

## Section-by-section design approval

Advance the design by section; do not dump a complete solution all at once. Common sections:
- Architecture。
- Core components。
- Data flow。
- Technology stack。
- Testing strategy。
- Risks and trade-offs。

Confirm only the applicable design sections. Complex changes usually need all six; narrow changes may omit sections that have no decision to make, but still require problem, impact scope, approach, and verification confirmation. Wait for user confirmation at the end of each section. When the user requests changes, revise only the current section and reconfirm before continuing.

**Testing Strategy**: When architectural changes affect existing tests, identify obsolete tests (update/delete/add), note which test suite is authoritative if multiple exist, and document in Design Summary. Classify each item as persistent (test suite) or one-time verification (no persistent test file). When one-time items exist, add a \`One-time Verification\` subsection.

## Design Summary self-review

Before generating the \`Design Summary\`, self-review:
- Are there unresolved scope questions?
- Are there placeholders, vague boundaries, or contradictory decisions?
- Are the testing strategy and risks explained?
- Does testing strategy include obsolete test handling when architectural changes affect existing tests?
- Are file writes, artifact updates, or subsequent generation actions left for non-explore workflows?

The \`Design Summary\` must stay in the conversation; do not create or update files. Content focuses on architecture, components, data flow, technology stack, testing strategy (with test maintenance when applicable), risks, and trade-offs.

## User review gate

After showing the \`Design Summary\` to the user, stop advancing; let the user review. When the user requests changes, return to the corresponding section and reconfirm.

Only route to xirang-propose after the user reviews and accepts the Design Summary.

## xirang-propose handoff

After the user confirms the \`Design Summary\`, hand off using tool-neutral workflow names:

\`\`\`
Design Summary complete. Review the above design. If confirmed, use xirang-propose to generate artifacts.
\`\`\`

Do not use tool-specific call syntax in references. Do not imply that explore can create proposals, update designs, modify Element Contracts, commit files, or directly enter implementation.`;

const DEFINITION_FRAMING_REFERENCE = `# Definition Framing Protocol

Definition Framing is an optional Change Formation stage for confirming structural targets before Design Exploration. It begins only when the user chooses it after the Agent recommends it for material or uncertain structural scope. This protocol owns structural framing and persistence only; the Superpowers-style reference continues to own the overall exploration conversation.

## Structural framing method

1. Start with a causal definition: state the structural problem, why the current structure causes it, and what semantic outcome the Change must create. Separate causes from symptoms and implementation preferences.
2. Clarify identity and boundaries before placement. For each proposed Element or Kind, define what it includes, what it excludes, and how it differs from nearby siblings. For a Relationship, define the source, target, and semantic meaning of its Kind.
3. Decompose the structure as a MECE set along a single structural dimension at a time. Do not mix lifecycle stage, responsibility, deployment location, and implementation technique in one sibling set. If the set is not mutually exclusive and collectively sufficient for the confirmed scope, revise the dimension before continuing.
4. Confirm in breadth-first (BFS) order: confirm the parent boundary, then the complete same-level structure, then descend one level. Do not finalize a child while unresolved siblings could change its identity or parent.
5. When identity, Kind, parent, or Relationship choices have multiple reasonable interpretations, present bounded alternatives with their semantic consequences and request one user decision. Re-run the affected MECE and BFS checks after a revision.

These steps govern structural decisions only. The Superpowers-style protocol still governs one-question conversation flow, overall option comparison, design section approval, and Design Summary handoff.

## Persistence boundary

- Persist only complete structural targets explicitly confirmed by the user: Element Kinds, Relationship Kinds, Element Declarations, and Relationships.
- A design-direction confirmation is not an explicit persistence confirmation. Before every create or update, show the complete current payload and ask separately whether to persist that exact payload.
- Use only \`xirang framing\` commands. Do not directly create, edit, rename, move, or delete the managed file.
- Do not persist Contract content, Authored Views, design rationale, implementation details, or the Design Summary.
- Every update is full replacement. Omitted targets are removed from the framing payload; deletion targets use only explicit \`operation: REMOVED\`.

## Lifecycle

1. Run \`xirang framing list --json\`. Resume the relevant record by immutable \`explorationId\`; do not infer identity from its slug or path.
2. For a new record, prepare the complete payload, obtain explicit persistence confirmation, then pass it on stdin to \`xirang framing create --slug <slug> --json\`.
3. Before resuming or replacing a record, run \`xirang framing show <explorationId> --json\`, \`xirang framing status <explorationId> --json\`, and \`xirang framing validate <explorationId> --json\`. On every resume, run all three before Design Exploration continues. Use \`show\` for the complete current payload, \`status\` for baseline drift, and \`validate\` for current impacts.
4. After confirmation of a replacement payload, pass the complete payload on stdin to \`xirang framing update <explorationId> --json\`. Never merge omitted fields locally.
5. Run \`xirang framing validate <explorationId> --json\` after create or update. Structural errors block Design Exploration. Contract and Authored View impacts require downstream design decisions but do not mutate those artifacts.
6. Use \`xirang framing rename <explorationId> --slug <slug> --json\` only for a confirmed label change. The immutable identity remains unchanged.
7. Use \`xirang framing discard <explorationId> --json\` only after explicit discard confirmation.

## Change handling

When a confirmed structural target changes, invalidate the affected structural confirmations and every downstream design decision that depends on them. Reconfirm the complete replacement payload first, then revisit the affected Contract, Authored View, data-flow, testing, and risk decisions. Unrelated design decisions remain valid.

The framing record is an intermediate Change Formation artifact. Propose compiles it into the canonical Semantic Delta and freezes it as historical provenance; it does not become a third normative Change component.`;

export function getExploreSkillTemplate(): SkillTemplate {
  return {
    name: 'xirang-explore',
    description: 'Enter explore mode - a thinking partner for exploring ideas, investigating problems, and clarifying requirements. Use when the user wants to think through something before or during a change.',
    referenceFiles: [
      {
        path: 'references/explore-supperpowers-style.md',
        content: EXPLORE_SUPPERPOWERS_STYLE_REFERENCE,
      },
      {
        path: 'references/definition-framing.md',
        content: DEFINITION_FRAMING_REFERENCE,
      },
    ],
    instructions: `Enter explore mode: investigate, clarify, compare, and help the user think before implementation.

${XIRANG_PHILOSOPHY}

## Workflow Stage

| Aspect | Value |
|--------|-------|
| **Stage** | \`EXPLORE\` - Design exploration with optional managed Definition Framing |
| **Allowed** | Read files, query CLI, ask questions, present options, Design Summary (conversation only), and use \`xirang framing\` after explicit persistence confirmation |
| **Forbidden** | Implement code or directly create, edit, or delete project or Change artifacts |

## Required References

- MUST read the project-root file \`.xirang/references/xirang-explore-supperpowers-style.md\` before exploring. DO NOT proceed without reading it first. It is the authoritative Superpowers brainstorming behavior guide for hard gate, context exploration, visual companion judgment, one-question discipline, options comparison, section approval, Design Summary review, and propose handoff.
- MUST read \`.xirang/references/xirang-definition-framing.md\` before offering or resuming Definition Framing. It is the authoritative Xirang-owned protocol for the only persisted Explore artifact.
- Do not reconstruct or duplicate Superpowers behavior from this prompt. Do not reconstruct or duplicate the Definition Framing protocol either. This prompt defines boundaries, context loading, semantic impact navigation, and proposal routing only.

## Hard Rules

- User confirmations ("ok", "option 2") approve design direction only, not file modification. Managed persistence requires a separate explicit persistence confirmation for the exact complete payload.
- Ask one clarification question at a time; do not auto-capture decisions into artifacts.
- When ready, produce a conversation-only \`Design Summary\` and instruct the user to call \`/xirang:propose <change-name>\`.

The main Explore agent remains read-only outside the managed Definition Framing exception. \`arch search\` and \`arch impact\` are read-only; they and the main agent MUST NOT create or update project or Change artifacts. Only \`xirang framing\` may persist the confirmed structural intermediate.

## Required Context

- Start with \`xirang list --json\`.
- Read relevant change artifacts when a change name is present.
- Use the Xirang Semantic Model for Project Root intent, refinement, Element Contracts, and semantic relationships; use live repository tools for code evidence.
- Ground claims in project files and git evidence when the idea maps to code.

${XIRANG_SHARED_CONTEXT}

${ELEMENT_DEFINITION_SEMANTICS}

${CONVERSATION_LANGUAGE_GUIDANCE}

## Semantic Impact

When a new module, workflow, command, configuration key, project concept, or unfamiliar domain term affects scope:
1. Run \`xirang arch search <query> --json\` against the Semantic Model.
2. Read the candidates in their Project Root and refinement context, then select one or more \`identity\` values as focus Elements. If no candidate or multiple plausible candidates remain, ask one clarification question instead of guessing.
3. Run \`xirang arch impact <identities...> --depth 2 --json\` to load refinement context, canonical Relationship paths, and complete Element Contracts.
4. Collect implementation evidence separately with CodeGraph, ACE, \`rg\`, and \`read\`; code paths, symbols, imports, and calls remain current implementation evidence only.
5. The main Explore agent combines user intent, Formal semantic context, and implementation evidence to judge \`mustChange\`, \`mustVerify\`, contextual scope, unknowns, and architecture drift. Relationship adjacency does not by itself prove a modification or verification conclusion.
6. Assess Element Definition impact only when an Element's concept identity or scope boundary changes. In that case, resolve the full concept and hierarchy boundary and include the complete target Definition in the Design Summary. Do not include a Definition rewrite for behavior-only or implementation-only changes.

Read active Change artifacts completely when one is in scope, but do not pass a Change or Semantic Delta to \`arch impact\`. Before proposal readiness, recheck the selected focus Elements and evidence coverage; disclose gaps instead of inferring missing evidence.

## Definition Framing and Design Exploration

Definition Framing is optional and begins only when the user chooses it. Recommend it when the structural scope is material or cannot be confirmed reliably inside the later design discussion; otherwise proceed directly to Design Exploration.

- Run \`xirang framing list --json\` before structural discussion. When the conversation selects a record, run \`xirang framing show <explorationId> --json\`, \`xirang framing status <explorationId> --json\`, and \`xirang framing validate <explorationId> --json\`. On every resume, run all three before Design Exploration continues. Use \`show\` for the complete current payload, \`status\` for baseline drift, and \`validate\` for current impacts.
- When a Change Structural Definition exists, Design Exploration must use its complete current payload and reported Contract and Authored View impacts. Do not reconstruct it from a Design Summary or a prior message.
- If a structural target changes, invalidate the affected structural confirmations and downstream design decisions, persist the explicitly confirmed complete replacement through the reference protocol, then reconfirm affected design sections.
- When no Change Structural Definition exists, continue from the Semantic Model and project evidence. Do not create an empty framing record.
- The Design Summary remains conversation-only. It may carry the \`explorationId\` for handoff, but it does not duplicate the structural payload.

## Simplicity Awareness

While exploring, build what's asked, but name the lazier alternative in one line when it exists. The user decides. Do not add a standalone simplicity review step — weave it into option comparison and section confirmation naturally.

The simplicity filter (for reference):
1. Does this need to exist at all? (YAGNI)
2. Does the standard library already do it? Use it.
3. Does a native platform feature cover it? Use it.
4. Does an already-installed dependency solve it? Use it.
5. Can it be one line? Make it one line.
6. Only then: the minimum that works.

## Brainstorming Checklist

If todo is available, create this checklist before context reads and tick each stage as completed. Explore MUST run this sequence before saying a proposal is ready:
1. **Explore project context**. Run \`xirang list --json\`, inspect relevant source and current implementation evidence, and identify affected subsystems. If the request spans multiple independent subsystems, identify them and recommend an implementation order.
2. **Decide whether a visual companion helps**. Use one only when it clarifies architecture, state, data flow, or trade-offs.
3. **Clarify one question at a time**. Ask exactly one question, then wait for the answer; resolve terminology before impact and design questions.
4. **Compare 2-3 options**. Present 2-3 viable approaches with strengths, weaknesses, best fit, and a recommendation when a real design choice exists. Name a simpler alternative in one line when applicable.
5. **Confirm the applicable design sections**. For a complex change, consider architecture, core components, data flow, technology stack, testing strategy, risks and trade-offs. For a narrow change, confirm at least the problem, impact scope, approach, and verification method. Classify testing items as persistent or one-time verification (no persistent test file); when one-time items exist, add a \`One-time Verification\` subsection.
6. **Self-review and generate Design Summary**. Resolve or explicitly defer scope-affecting questions, recheck semantic impact context, and check for contradictions and vague boundaries. Produce the conversation-only \`Design Summary\`. Present the Design Summary, then end with: "Design Summary complete. Review the above design. If confirmed, call \`/xirang:propose <change-name>\` generate artifacts." After presenting the Design Summary, STOP — do not offer to run a workflow or ask follow-up questions. Only the user triggers the next workflow.

## Existing Changes

${ACTIVE_CHANGE_CAPTURE_GUIDANCE}`,
    license: 'MIT',
    compatibility: 'Requires xirang CLI.',
    metadata: { author: 'xirang', version: '1.0' },
  };
}
