/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate } from '../types.js';
import {
  XIRANG_PHILOSOPHY,
  XIRANG_SHARED_CONTEXT,
} from '../fragments/xirang-fragments.js';

const CONVERSATION_LANGUAGE_GUIDANCE = `Output language: use the user's main language for prose and non-canonical section labels; keep commands, paths, artifact names, schema keys, and Xirang tokens unchanged.`;

const ACTIVE_CHANGE_CAPTURE_GUIDANCE = `### Capture Boundary for Existing Changes

When exploring an active change, read proposal/design/tasks and its Delta units, reference them naturally, and classify insights by where a future workflow should capture them. Do not update those artifacts in explore.

| Insight Type                         | Future Capture Target                          |
|--------------------------------------|------------------------------------------------|
| Observable behavior requirement      | \`elements/<identity>.md\` body                 |
| Observable behavior changed          | \`elements/<identity>.md\` body                 |
| Refactor rationale or rejected path  | \`design.md\`                                   |
| Implementation strategy              | \`design.md\`                                   |
| Scope changed                        | \`proposal.md\`                                 |
| New work or verification identified  | \`tasks.md\`                                    |
| Element identity or hierarchy changed | \`elements/<identity>.md\` frontmatter          |
| Relationship changed                 | \`relationships/<relationship kind identity>.yaml\` |
| Element Kind or Relationship Kind changed | \`metamodel/<kind identity>.md\`           |
| Authored View changed                | \`views/<view identity>.md\`                    |
| Assumption invalidated               | Relevant artifact                              |
| Test needs update or deletion        | \`tasks.md\` + \`design.md\`                     |

Example offers:
- "That is a design decision for \`design.md\`; include it in the Design Summary, then call \`/xirang:propose <change-name>\` or the appropriate non-explore workflow."
- "This changes an Element Contract; include it in the Design Summary, then call \`/xirang:propose <change-name>\` or the appropriate non-explore workflow."
- "This changes scope for \`proposal.md\`; include it in the Design Summary, then call \`/xirang:propose <change-name>\` or the appropriate non-explore workflow."`;

const EXPLORE_SUPPERPOWERS_STYLE_REFERENCE = `# Superpowers-Style Explore Behavior Guide

This reference is the Xirang explore adaptation of Superpowers brainstorming. It restores design-first discipline but does not restore original Superpowers file writing, committing, or implementation planning permissions.

## Superpowers brainstorming source

The core of Superpowers brainstorming is not free-form discussion, but compressing vague ideas into user-confirmed designs before implementation:
- Read project context first, then determine problem boundaries.
- Ask exactly one clarification question at a time.
- For key choices, present 2-3 approaches with trade-offs and a recommendation.
- Present design section by section; wait for user confirmation on each.
- Self-review the design, then hand off for user review.
- Enter the next workflow through explicit handoff.

If todo is available, track these stages as a checklist and tick each completed stage.

Xirang mapping:
- The original design-document step maps to a conversation-only \`Design Summary\`.
- The original commit step is removed; explore does not write files.
- The original implementation-plan handoff maps to \`xirang-propose\` handoff.

## Conversation language

${CONVERSATION_LANGUAGE_GUIDANCE}

## Hard gate before implementation

Do not implement before design confirmation is complete.

Do not start coding, generate patches, update artifacts, or interpret design confirmations as write authorization during Explore. Even if the user says "ok", "that works", or chooses an option, it only confirms the design direction.

Simple changes still require design confirmation. For a narrow change, confirm only the applicable design sections, but do not skip the process: at minimum confirm the problem, impact scope, approach, and verification method.

## Project context exploration

**Evidence-first discipline**: All claims about existing code, architecture, or technical decisions must be grounded in project evidence. Do not substitute general knowledge for project facts.

Before context reads, create the todo checklist: context, visual decision, one question, options, section approvals, self-review, handoff.

Constrain the discussion with project facts first:
- Read relevant Xirang change, Element Contract, design, and tasks.
- Inspect relevant implementation files, tests, and git evidence.
- Identify affected subsystems; if the request spans multiple independent subsystems, first clarify boundaries and recommend an order.
- Explicitly identify unknowns; do not substitute general experience for project evidence.

## Just-in-time visual companion

Use visual expression only when it reduces complexity. Suitable scenarios:
- Architectural boundaries, state machines, data flow, dependency relationships.
- Multi-option comparison.
- When the user is stuck on abstract relationships.

For routine CLI behavior, narrow fixes, field naming, or test selection, use concise text or tables; do not introduce a browser or server companion.

## One-question discipline

Ask only one design-changing question per turn, then wait for the answer. Do not bundle scope, API, data model, and testing strategy into a string of questions.

If the choice set is clear, prefer presenting 2-3 options with differences explained; if unclear, first ask one question that narrows the problem space.

## 2-3 approaches

Provide 2-3 approaches for key design decisions. Each option includes:
- Description.
- Strengths.
- Weaknesses or risks.
- Best-fit scenario.

When giving a recommendation, explain why and tie it to project constraints, not personal preference.

## Section-by-section design approval

Advance the design by section; do not dump a complete solution all at once. Common sections:
- Architecture。
- Core components。
- Data flow。
- Technology stack。
- Testing strategy。
- Risks and trade-offs。

Confirm only the applicable design sections. Complex changes usually need all six; narrow changes may omit sections that have no decision to make, but still require problem, impact scope, approach, and verification confirmation. Wait for user confirmation at the end of each section. When the user requests changes, revise only the current section and reconfirm before continuing.

**Testing Strategy**: When architectural changes affect existing tests, identify obsolete tests (update/delete/add), note which test suite is authoritative if multiple exist, and document in Design Summary. Classify each item as persistent (test suite) or one-time verification (no persistent test file). When one-time items exist, add a \`One-time Verification\` subsection.

## Design Summary self-review

Before generating the \`Design Summary\`, self-review:
- Are there unresolved scope questions?
- Are there placeholders, vague boundaries, or contradictory decisions?
- Are the testing strategy and risks explained?
- Does testing strategy include obsolete test handling when architectural changes affect existing tests?
- Are file writes, artifact updates, or subsequent generation actions left for non-explore workflows?

The \`Design Summary\` must stay in the conversation; do not create or update files. Content focuses on architecture, components, data flow, technology stack, testing strategy (with test maintenance when applicable), risks, and trade-offs.

## User review gate

After showing the \`Design Summary\` to the user, stop advancing; let the user review. When the user requests changes, return to the corresponding section and reconfirm.

Only route to xirang-propose after the user reviews and accepts the Design Summary.

## xirang-propose handoff

After the user confirms the \`Design Summary\`, hand off using tool-neutral workflow names:

\`\`\`
Design Summary complete. Review the above design. If confirmed, use xirang-propose to generate artifacts.
\`\`\`

Do not use tool-specific call syntax in references. Do not imply that explore can create proposals, update designs, modify Element Contracts, commit files, or directly enter implementation.`;

export function getExploreSkillTemplate(): SkillTemplate {
  return {
    name: 'xirang-explore',
    description: 'Enter explore mode - a thinking partner for exploring ideas, investigating problems, and clarifying requirements. Use when the user wants to think through something before or during a change.',
    referenceFiles: [
      {
        path: 'references/explore-supperpowers-style.md',
        content: EXPLORE_SUPPERPOWERS_STYLE_REFERENCE,
      },
    ],
    instructions: `Enter explore mode: investigate, clarify, compare, and help the user think before implementation.

${XIRANG_PHILOSOPHY}

## Workflow Stage

| Aspect | Value |
|--------|-------|
| **Stage** | \`EXPLORE\` - Read-only brainstorming |
| **Allowed** | Read files, query CLI, ask questions, present options, Design Summary (conversation only) |
| **Forbidden** | Create, edit, delete any file or artifact |

## Required References

- MUST read the project-root file \`.xirang/references/xirang-explore-supperpowers-style.md\` before exploring. DO NOT proceed without reading it first. It is the authoritative Superpowers brainstorming behavior guide for hard gate, context exploration, visual companion judgment, one-question discipline, options comparison, section approval, Design Summary review, and propose handoff.
- Do not reconstruct or duplicate Superpowers behavior from this prompt. This prompt defines boundaries, context loading, semantic impact navigation, and proposal routing only.

## Hard Rules

- User confirmations ("ok", "option 2") approve design direction only, not file modification.
- Ask one clarification question at a time; do not auto-capture decisions into artifacts.
- When ready, produce a conversation-only \`Design Summary\` and instruct the user to call \`/xirang:propose <change-name>\`.

The main Explore agent remains read-only. \`arch search\` and \`arch impact\` are read-only; they and the main agent MUST NOT create or update project files.

## Required Context

- Start with \`xirang list --json\`.
- Read relevant change artifacts when a change name is present.
- Use the Xirang Semantic Model for Project Root intent, refinement, Element Contracts, and semantic relationships; use live repository tools for code evidence.
- Ground claims in project files and git evidence when the idea maps to code.

${XIRANG_SHARED_CONTEXT}

${CONVERSATION_LANGUAGE_GUIDANCE}

## Semantic Impact

When a new module, workflow, command, configuration key, project concept, or unfamiliar domain term affects scope:
1. Run \`xirang arch search <query> --json\` against the Formal Semantic Model.
2. Read the candidates in their Project Root and refinement context, then select one or more \`identity\` values as focus Elements. If no candidate or multiple plausible candidates remain, ask one clarification question instead of guessing.
3. Run \`xirang arch impact <identities...> --depth 2 --json\` to load refinement context, canonical Relationship paths, and complete Element Contracts.
4. Collect implementation evidence separately with CodeGraph, ACE, \`rg\`, and \`read\`; code paths, symbols, imports, and calls remain current implementation evidence only.
5. The main Explore agent combines user intent, Formal semantic context, and implementation evidence to judge \`mustChange\`, \`mustVerify\`, contextual scope, unknowns, and architecture drift. Relationship adjacency does not by itself prove a modification or verification conclusion.

Read active Change artifacts completely when one is in scope, but do not pass a Change or Semantic Delta to \`arch impact\`. Before proposal readiness, recheck the selected focus Elements and evidence coverage; disclose gaps instead of inferring missing evidence.

## Simplicity Awareness

While exploring, build what's asked, but name the lazier alternative in one line when it exists. The user decides. Do not add a standalone simplicity review step — weave it into option comparison and section confirmation naturally.

The simplicity filter (for reference):
1. Does this need to exist at all? (YAGNI)
2. Does the standard library already do it? Use it.
3. Does a native platform feature cover it? Use it.
4. Does an already-installed dependency solve it? Use it.
5. Can it be one line? Make it one line.
6. Only then: the minimum that works.

## Brainstorming Checklist

If todo is available, create this checklist before context reads and tick each stage as completed. Explore MUST run this sequence before saying a proposal is ready:
1. **Explore project context**. Run \`xirang list --json\`, inspect relevant source and current implementation evidence, and identify affected subsystems. If the request spans multiple independent subsystems, identify them and recommend an implementation order.
2. **Decide whether a visual companion helps**. Use one only when it clarifies architecture, state, data flow, or trade-offs.
3. **Clarify one question at a time**. Ask exactly one question, then wait for the answer; resolve terminology before impact and design questions.
4. **Compare 2-3 options**. Present 2-3 viable approaches with strengths, weaknesses, best fit, and a recommendation when a real design choice exists. Name a simpler alternative in one line when applicable.
5. **Confirm the applicable design sections**. For a complex change, consider architecture, core components, data flow, technology stack, testing strategy, risks and trade-offs. For a narrow change, confirm at least the problem, impact scope, approach, and verification method. Classify testing items as persistent or one-time verification (no persistent test file); when one-time items exist, add a \`One-time Verification\` subsection.
6. **Self-review and generate Design Summary**. Resolve or explicitly defer scope-affecting questions, recheck semantic impact context, and check for contradictions and vague boundaries. Produce the conversation-only \`Design Summary\`. Present the Design Summary, then end with: "Design Summary complete. Review the above design. If confirmed, call \`/xirang:propose <change-name>\` generate artifacts." After presenting the Design Summary, STOP — do not offer to run a workflow or ask follow-up questions. Only the user triggers the next workflow.

## Existing Changes

${ACTIVE_CHANGE_CAPTURE_GUIDANCE}`,
    license: 'MIT',
    compatibility: 'Requires xirang CLI.',
    metadata: { author: 'xirang', version: '1.0' },
  };
}
