/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate } from '../types.js';
import {
  ARTIFACT_DOC_LANGUAGE_CONTRACT,
  OPSX_CLI_QUERY_CONTEXT,
  OPSX_COMPILATION_PHILOSOPHY,
  OPSX_SHARED_CONTEXT,
} from '../fragments/opsx-fragments.js';

export function getOpsxProposeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-propose',
    description: 'Propose a new change with all artifacts generated in one step. Use when the user wants to quickly describe what they want to build and get a complete proposal with design, specs, and tasks ready for implementation.',
    instructions: `Propose a new change and generate all artifacts needed for implementation.

${OPSX_COMPILATION_PHILOSOPHY}

## Workflow Stage

| Aspect | Value |
|--------|-------|
| **Stage** | \`PROPOSE\` - Artifact generation (no implementation) |
| **Allowed** | Generate proposal, design, specs, tasks, opsx-delta in openspec/changes/<name>/ |
| **Forbidden** | Implement code, modify existing project files |

## Flow

1. Input must identify a kebab-case change name or enough description to derive one. If unclear, ask what to build or fix.
2. Apply smart routing before creating files: inspect the current conversation for an explore-generated \`Design Summary\`; if no summary exists, respect \`propose.smartRouting: false\` and \`propose.requireExplore: false\`, otherwise score the user's input across 5 dimensions. Detect multi-subsystem scope. Outcomes include: "Design Summary found: proceed and show that Design Summary is being used", "Input is sufficiently detailed. Skipping explore; generating artifacts directly.", and "This request spans multiple independent subsystems. Consider running \`/opsx:explore\` to decompose it first.". Show input length, detail score, multi-subsystem result, and final decision. For a **One-time Verification** subsection, route items to \`tasks.md\` Checks (no persistent test file; absence assertions use \`Verifies: <path> REMOVED Requirement\`).
3. Run \`openspec new change "<name>"\`, then \`openspec status --change "<name>" --json\` to read \`applyRequires\`, artifact order, dependencies, and schema.
4. Load shared OPSX context before artifact generation.
${OPSX_SHARED_CONTEXT}
5. Before specs, run \`openspec list --specs --json\`; compare proposed capabilities to each spec's \`capabilities\` string array. Specs without frontmatter return \`capabilities: []\`. Reuse or modify existing coverage instead of duplicating specs.
6. Use CLI-backed OPSX navigation after shared context.
${OPSX_CLI_QUERY_CONTEXT}
7. For each ready artifact, run \`openspec instructions <artifact-id> --change "<name>" --json\`; read \`configProjection\` (especially \`configProjection.normalized.proseLanguage\` and \`configProjection.prompt.fragments\`), dependencies, \`template\`, \`instruction\`, and \`outputPath\`; follow the template exactly and do not copy \`context\`, \`rules\`, or \`configProjection\` into artifact files. Before writing change-local specs, run \`openspec check-delta --change "<name>" --caps <spec-id> --added <header> --modified <header> --removed <header> --renamed-from <header>\` with target spec ids and planned requirement headers. Missing and Conflict results are blocking before writing specs; post-write validation remains warning-only. When creating \`specs\`, apply the returned \`Spec content boundary\`: route non-behavior content to design/tasks/proposal/opsx-delta instead of requirements. Scenario operation labels are change-local metadata only: use \`#### Scenario: [ADDED] <title>\`, \`#### Scenario: [MODIFIED] <title>\`, or \`#### Scenario: [REMOVED] <title>\` in change specs; sync/archive strip or omit them, and formal specs MUST NOT contain them.
8. Continue until all \`applyRequires\` artifacts are \`done\`. If an artifact is unclear, ask one focused question and continue.
9. After spec-driven specs are complete, generate \`opsx-delta.yaml\` from \`openspec instructions opsx-delta --change "<name>" --json\`; use \`schema_version: 1\`, \`ADDED:\`, \`MODIFIED:\`, and \`REMOVED:\` YAML keys and query existing nodes when needed.
10. Run warning-only post-propose validation: This validation is warning-only. Do NOT turn \`/opsx:propose\` into a blocking gate. Use staged checks: \`openspec validate --change "<name>" --artifacts specs --json\` for generated specs and \`openspec validate --change "<name>" --artifacts opsx-delta --json\` for \`opsx-delta.yaml\`; then use \`openspec validate --change "<name>" --json\` for full change validation. Align with \`Validator.validateChangeDeltaSpecs()\`, SHALL/MUST requirement text, required \`#### Scenario:\` blocks, \`Validator.validateOpsxDelta()\`, \`applyOpsxDelta()\`, referential integrity, and code-map integrity. Do NOT run \`openspec sync\`; report when validation skips this check. For structure checks, read \`openspec instructions proposal --change "<name>" --json\`, \`openspec instructions design --change "<name>" --json\`, and \`openspec instructions tasks --change "<name>" --json\`; use \`validateTaskStructure\`, support Actions and coarse \`### Task N:\` with Goal, Files, Requirements, Checks, Covers:, Verifies:, change-local \`Verifies:\` spec paths, Requirement/Scenario references, Command:, Evidence:, and Expect:. Do NOT invent semantic lint rules beyond the current templates. Do NOT judge whether a check is semantically sufficient. If warnings appear, do exactly one repair pass, re-check once, and summarize remaining warnings.
11. Finish with \`openspec status --change "<name>"\` and report artifacts created plus readiness for \`/opsx:apply\`.

## Artifact Contract

${ARTIFACT_DOC_LANGUAGE_CONTRACT}

Keep generated tasks coarse: \`### Task N:\`, \`Goal\`, \`Files\`, \`Requirements\`, and nested Checks. Keep each task to at most 5 Requirements. Preserve template structure, canonical headings, IDs, schema keys, paths, commands, BDD keywords, and code identifiers.`,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}
